# Generated by Django 4.0.3 on 2022-04-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Onkabu',
            new_name='Portfolio',
        ),
    ]
