# Generated by Django 4.0.3 on 2022-04-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_onkabu_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='bool_value',
            new_name='book_value',
        ),
    ]
