# Generated by Django 4.0.3 on 2022-05-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='uid',
            field=models.CharField(default='', max_length=48),
        ),
    ]
